//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ioasys.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ioasys.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voce so pode alterar o seu proprio Usuario..
        /// </summary>
        public static string EditarSemPermissao {
            get {
                return ResourceManager.GetString("EditarSemPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filme informado nao existe.
        /// </summary>
        public static string FilmeInexistente {
            get {
                return ResourceManager.GetString("FilmeInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voce nao tem permicao para inativar usuarios..
        /// </summary>
        public static string InativarSemPermissao {
            get {
                return ResourceManager.GetString("InativarSemPermissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha e/ou usuario nao encontrados.
        /// </summary>
        public static string LoginInvalido {
            get {
                return ResourceManager.GetString("LoginInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voce nao possui permicao para registrar Filmes.
        /// </summary>
        public static string RegistrarFilmeSemPermissao {
            get {
                return ResourceManager.GetString("RegistrarFilmeSemPermissao", resourceCulture);
            }
        }
    }
}
